FROM vllm/vllm-openai:v0.16.0
RUN LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LIBRARY_PATH} pip install kvcached --no-build-isolation

ENV ENABLE_KVCACHED=true
ENV KVCACHED_AUTOPATCH=1
ENV KVCACHED_IPC_NAME=VLLM

EXPOSE 8080 12346 30000 30001

ENTRYPOINT []
CMD ["bash"]